#!/bin/bash

# Backup the current resolv.conf
sudo cp /etc/resolv.conf /etc/resolv.conf.backup

# List of public DNS servers to add
DNS_SERVERS=(
    "8.8.8.8"   # Google
    "8.8.4.4"   # Google
    "1.1.1.1"   # Cloudflare
    "1.0.0.1"   # Cloudflare
    "9.9.9.9"   # Quad9
    "149.112.112.112" # Quad9
    "208.67.222.222"  # OpenDNS
    "208.67.220.220"  # OpenDNS
    "64.6.64.6"   # Verisign
    "64.6.65.6"   # Verisign
)

# Write DNS servers to resolv.conf
{
    echo "# Generated by add_dns_servers.sh"
    for dns in "${DNS_SERVERS[@]}"; do
        echo "nameserver $dns"
    done
} | sudo tee /etc/resolv.conf

# Display the new resolv.conf
echo "Updated /etc/resolv.conf:"
cat /etc/resolv.conf
