#!/bin/bash

# Array of 20 DNS servers to be added
DNS_SERVERS=(
    "8.8.8.8"         # Google DNS
    "8.8.4.4"         # Google DNS
    "1.1.1.1"         # Cloudflare DNS
    "1.0.0.1"         # Cloudflare DNS
    "9.9.9.9"         # Quad9
    "149.112.112.112" # Quad9
    "208.67.222.222"  # OpenDNS
    "208.67.220.220"  # OpenDNS
    "64.6.64.6"       # Verisign
    "64.6.65.6"       # Verisign
    "8.26.56.26"      # Comodo Secure DNS
    "8.20.247.20"     # Comodo Secure DNS
    "185.228.168.9"   # CleanBrowsing
    "185.228.169.9"   # CleanBrowsing
    "198.101.242.72"  # Alternate DNS
    "23.253.163.53"   # Alternate DNS
    "77.88.8.8"       # Yandex DNS
    "77.88.8.1"       # Yandex DNS
    "156.154.70.1"    # Neustar DNS
    "156.154.71.1"    # Neustar DNS
)

# Backup the current resolv.conf
cp /etc/resolv.conf /etc/resolv.conf.bak

# Add new DNS servers to resolv.conf
{
    echo "# Generated by add_dns_servers.sh"
    for dns in "${DNS_SERVERS[@]}"; do
        echo "nameserver $dns"
    done
} > /etc/resolv.conf

echo "DNS servers have been updated."
